---
gitRepo: "ArcBlock/forge-tutorials"
srcPath: "src"
categories:
  tutorials:
    basePath: "/tutorials"
    title: "Tutorials"
    link: "/"
    priority: 999
    sidebar:
      "null":
        - "/"
      Upgrade Forge:
        - "/hard-upgrade"
        - "/soft-upgrade"
      Deploy Forge:
        - "/deployment/intranet"
      XMark:
        - "/xmark-kitchen-sink"
