gitRepo: ArcBlock/forge-cli-handbook
srcPath: src
categories:
  handbook:
    basePath: /handbook
    title: HandBook
    link: /
    priority: 999
    sidebar:
      "null":
        - /
      Introduction:
        links:
          - /1-introduction
          - /1-introduction/what-is-forge-cli
          - /1-introduction/why-forge-cli
          - /1-introduction/install-forge-cli
          - /1-introduction/getting-started
          - /1-introduction/initial-setup
        locales:
          zh: '入门'
      Forge Release Management:
        links:
          - /4-manage-forge-release
          - /4-manage-forge-release/find-release
          - /4-manage-forge-release/download-install-release
        locales:
          zh: 'Forge 版本管理'
      Chain/Node Management:
        links:
          - /2-manage-chain-node
          - /2-manage-chain-node/create-config-chain
          - /2-manage-chain-node/start-stop-chain
          - /2-manage-chain-node/inspect-chain-status
          - /2-manage-chain-node/view-chain-log
          - /2-manage-chain-node/upgrade-chain
          - /2-manage-chain-node/reset-remove-chain
        locales:
          zh: '链节点管理'
      Manipulate Wallets/Accounts:
        links:
          - /5-manipulate-wallets-accounts
          - /5-manipulate-wallets-accounts/local-wallets
        locales:
          zh: '使用钱包和账户'
      Read/Write on Chain Data:
        links:
          - /3-read-write-on-chain-data
          - /3-read-write-on-chain-data/inspect-accounts
          - /3-read-write-on-chain-data/inspect-transactions
          - /3-read-write-on-chain-data/inspect-blocks
          - /3-read-write-on-chain-data/inspect-assets
          - /3-read-write-on-chain-data/inspect-contracts
        locales:
          zh: '读写链上数据'
      Working with Contracts:
        links:
          - /6-working-with-contracts
          - /6-working-with-contracts/compile-deploy-contract
          - /6-working-with-contracts/create-own-contract
          - /6-working-with-contracts/activate-deactivate-contract
        locales:
          zh: '使用智能合约'
      Working with Blocklets:
        links:
          - /7-working-with-blocklets
          - /7-working-with-blocklets/what-are-blocklets
          - /7-working-with-blocklets/dapp-blocklets
          - /7-working-with-blocklets/starter-blocklets
          - /7-working-with-blocklets/contract-blocklets
          - /7-working-with-blocklets/creating-blocklet
        locales:
          zh: '使用基石程序'
      Explore Other Tooling:
        links:
          - /8-explorer-other-tooling
          - /8-explorer-other-tooling/forge-web
          - /8-explorer-other-tooling/simulator
          - /8-explorer-other-tooling/dapp-workshop
          - /8-explorer-other-tooling/forge-swap-service
        locales:
          zh: '探索其他工具'
      Use Forge CLI in Production:
        links:
          - /11-forge-cli-in-production
          - /11-forge-cli-in-production/join-existing-network
          - /11-forge-cli-in-production/deploy-multi-node-network
          - /11-forge-cli-in-production/deploy-multi-party-network
          - /11-forge-cli-in-production/deploy-in-intranet
        locales:
          zh: '生产环境指南'
      Customization:
        links:
          - /9-customization/global-config
          - /9-customization/multi-chain
        locales:
          zh: '高级用法'
      Troubleshooting:
        links:
          - /10-troubleshooting
        locales:
          zh: '问题诊断'
